import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans, Poppins } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { Footer } from "./components/footer";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-nunito-sans',
  weight: ['200','300','400', '600', '700'], // Choose weights you need
});

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['200','300','400', '600', '700'],
});

export const metadata: Metadata = {
  title: "CityVision",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${nunitoSans.variable} ${poppins.variable} antialiased`}
        >
            <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
